from app.models.tables import (
    AvoirOption,
    Clinicien,
    Comercant,
    ComposerDe,
    Composant,
    Consultation,
    EstAssocie,
    Fauteuil,
    Morphologie,
    Option,
    Pathologie,
    Patient,
    PatientMedical,
    TypeFauteuil,
    UserPreferences,
    Utilisateur,
)

__all__ = [
    "Utilisateur",
    "Patient",
    "Clinicien",
    "Comercant",
    "Fauteuil",
    "TypeFauteuil",
    "Pathologie",
    "Morphologie",
    "Composant",
    "Option",
    "AvoirOption",
    "ComposerDe",
    "EstAssocie",
    "Consultation",
    "Composant",
    "UserPreferences",
    "PatientMedical",
]
